// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/hwl/im/protocol/im_message.proto

package com.hwl.im.core.proto;

public interface ImChatGroupMessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ImChatGroupMessageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ImChatGroupMessageContent chatGroupMessageContent = 1;</code>
   */
  boolean hasChatGroupMessageContent();
  /**
   * <code>.ImChatGroupMessageContent chatGroupMessageContent = 1;</code>
   */
  com.hwl.im.core.proto.ImChatGroupMessageContent getChatGroupMessageContent();
  /**
   * <code>.ImChatGroupMessageContent chatGroupMessageContent = 1;</code>
   */
  com.hwl.im.core.proto.ImChatGroupMessageContentOrBuilder getChatGroupMessageContentOrBuilder();

  /**
   * <code>uint64 buildTime = 2;</code>
   */
  long getBuildTime();
}
