// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/hwl/im/protocol/im_message.proto

package com.hwl.im.core.proto;

public interface ImMessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ImMessageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ImMessageResponseHead responseHead = 1;</code>
   */
  boolean hasResponseHead();
  /**
   * <code>.ImMessageResponseHead responseHead = 1;</code>
   */
  com.hwl.im.core.proto.ImMessageResponseHead getResponseHead();
  /**
   * <code>.ImMessageResponseHead responseHead = 1;</code>
   */
  com.hwl.im.core.proto.ImMessageResponseHeadOrBuilder getResponseHeadOrBuilder();

  /**
   * <code>.ImUserValidateResponse userValidateResponse = 2;</code>
   */
  boolean hasUserValidateResponse();
  /**
   * <code>.ImUserValidateResponse userValidateResponse = 2;</code>
   */
  com.hwl.im.core.proto.ImUserValidateResponse getUserValidateResponse();
  /**
   * <code>.ImUserValidateResponse userValidateResponse = 2;</code>
   */
  com.hwl.im.core.proto.ImUserValidateResponseOrBuilder getUserValidateResponseOrBuilder();

  /**
   * <code>.ImChatUserMessageResponse chatUserMessageResponse = 3;</code>
   */
  boolean hasChatUserMessageResponse();
  /**
   * <code>.ImChatUserMessageResponse chatUserMessageResponse = 3;</code>
   */
  com.hwl.im.core.proto.ImChatUserMessageResponse getChatUserMessageResponse();
  /**
   * <code>.ImChatUserMessageResponse chatUserMessageResponse = 3;</code>
   */
  com.hwl.im.core.proto.ImChatUserMessageResponseOrBuilder getChatUserMessageResponseOrBuilder();

  /**
   * <code>.ImChatGroupMessageResponse chatGroupMessageResponse = 4;</code>
   */
  boolean hasChatGroupMessageResponse();
  /**
   * <code>.ImChatGroupMessageResponse chatGroupMessageResponse = 4;</code>
   */
  com.hwl.im.core.proto.ImChatGroupMessageResponse getChatGroupMessageResponse();
  /**
   * <code>.ImChatGroupMessageResponse chatGroupMessageResponse = 4;</code>
   */
  com.hwl.im.core.proto.ImChatGroupMessageResponseOrBuilder getChatGroupMessageResponseOrBuilder();

  public com.hwl.im.core.proto.ImMessageResponse.ResponseBodyCase getResponseBodyCase();
}
