// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/hwl/im/protocol/im_message.proto

package com.hwl.im.core.proto;

public interface ImMessageContextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ImMessageContext)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ImMessageType type = 1;</code>
   */
  int getTypeValue();
  /**
   * <code>.ImMessageType type = 1;</code>
   */
  com.hwl.im.core.proto.ImMessageType getType();

  /**
   * <code>.ImMessageRequest request = 2;</code>
   */
  boolean hasRequest();
  /**
   * <code>.ImMessageRequest request = 2;</code>
   */
  com.hwl.im.core.proto.ImMessageRequest getRequest();
  /**
   * <code>.ImMessageRequest request = 2;</code>
   */
  com.hwl.im.core.proto.ImMessageRequestOrBuilder getRequestOrBuilder();

  /**
   * <code>.ImMessageResponse response = 3;</code>
   */
  boolean hasResponse();
  /**
   * <code>.ImMessageResponse response = 3;</code>
   */
  com.hwl.im.core.proto.ImMessageResponse getResponse();
  /**
   * <code>.ImMessageResponse response = 3;</code>
   */
  com.hwl.im.core.proto.ImMessageResponseOrBuilder getResponseOrBuilder();

  public com.hwl.im.core.proto.ImMessageContext.BodyCase getBodyCase();
}
